version: '3.7'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: test-php-dev-nginx
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/var/www/html:cached
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    networks:
      - test-php-dev
    ports:
      - 32777:80
  php:
    build:
      dockerfile: Dockerfile
      context: build/php
    container_name: test-php-dev-fpm
    environment:
      - LOCAL_USER_ID=${HOST_UID}
      - APP_ENV=dev
    volumes:
      - ./:/var/www/html:cached
    networks:
      - test-php-dev

networks:
  test-php-dev:
    name: test-php-dev